### ISSUE TITLE
[Bug report] A few errors with Iwagawa Airfield server after running test.

### ISSUE THREAD

**Issue by ghost** [LostLogia4/KancolleLoader#11] opened 2016-01-19 23:51 UTC
Hi @LostLogia4, tried reaching you through the you-know-where gitter chat. So instead I have decided to upload the information from the test result I ran just minutes ago here.

My `git pull` log:

```
$ git pull
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 33 (delta 20), reused 27 (delta 14), pack-reused 0
Unpacking objects: 100% (33/33), done.
From https://github.com/LostLogia4/KancolleLoader
   a768d99..527387c  master     -> origin/master
Your configuration specifies to merge with the ref 'refs/heads/releasefix'
from the remote, but no such ref was fetched.
$
```

My version of KancolleLoader: commit c5085373e1b278498099c8ffe560b2905b8c45c9

![screenshot_20160120_094842](https://cloud.githubusercontent.com/assets/12234182/12435763/4dcc04c6-bf5b-11e5-9fcd-80196b5375be.png)

**Comment by LostLogia4** [comment] 2016-01-20 03:05
Caused by obsolete api_shipgraph data, [should be fixed now](https://github.com/LostLogia4/KancolleLoader/commit/56cdc51d1c370fb15e8fb4b185570683e6fbe978).

(yes, the devs CHANGED the swf links!)

**Closed as completed by LostLogia4** 2016-01-20 03:05 UTC
Labels: bug
